version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Taipei  # 設定時區為台灣時區
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_backup:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    container_name: my_backend_container
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - "5001:5000"

volumes:
  db_data:
